[profile.release]
opt-level = 'z'                             # Optimize for size
lto = true                                  # Enable link-time optimization
codegen-units = 1                           # Reduce number of codegen units to increase optimizations
panic = 'abort'                             # Abort on panic
strip = true                                # Strip symbols from binary*


[target.armv5te-none-eabi]                # All targets
rustflags = ["-C", "linker-flavor=ld.lld","-C", "link-arg=-Tlinkerscripts/link_arm9_installer.x"]


[build]
target = "armv5te-none-eabi"
target-dir = "../../../target-installer"

[unstable]
build-std = ["core", "alloc"]
