[profile.release]
opt-level = 'z'                             # Optimize for size
lto = true                                  # Enable link-time optimization
codegen-units = 1                           # Reduce number of codegen units to increase optimizations
panic = 'abort'                             # Abort on panic
strip = true                                # Strip symbols from binary*

[target.armv4t-none-eabi]                # All targets
rustflags = ["-C", "linker-flavor=ld.lld","-C", "link-arg=-Tlinkerscripts/link_arm7.x"]

[build]
target = "armv4t-none-eabi"
target-dir = "../../../target-binary"

[unstable]
build-std = ["core", "alloc"]
