#[repr(C)]
pub struct Config {
    //flags
    pub config_flags: u32,
    _0x4: u8,
    pub country: u8,
    pub language: u8,
    pub rtc_year: u8,
    pub rtc_offset: i64,
    pub eula: [u8; 8],
    _0x18: [u8; 2],
    pub alarm_hour: u8,
    pub alarm_minute: u8,
    _0x1c: [u8; 2],
    pub alarm_enable: u8,
    _0x1f: [u8; 2],
    pub system_menu_used_slots: u8,
    pub system_menu_free_slots: u8,
    _0x23: u8,
    _0x24: u8,
    _0x25: [u8; 3],
    pub last_selected_tid: u64,
    //touch calibration 
    pub tc_x1_adc: u16,
    pub tc_y1_adc: u16,
    pub tc_x1_pixrl: u8,
    pub tc_y1_pixrl: u8,
    pub tc_x2_adc: u16,
    pub tc_y2_adc: u16,
    pub tc_x2_pixrl: u8,
    pub tc_y2_pixrl: u8,
    _0x3c: u32,
    _0x40: [u8; 4],
    //profile
    pub favorite_color: u8,
    _0x45: u8,
    pub birth_month: u8,
    pub birth_day: u8,
    pub nickname: [u16; 11],
    pub message: [u16; 27],
    //parental controls
    pub pc_flags: u8,
    _0x95: [u8; 6],
    pub pc_region: u8,
    pub pc_age: u8,
    pub pc_secret_question: u8,
    pub pc_unknown: u8,
    _0x9f: [u8; 2],
    pub pc_pin: [u8; 5],
    pub pc_secret_answer: [u16; 65],
}